### ISSUE TITLE
两个滚动列表怎么联动

### ISSUE THREAD

**Issue by dnoyeb** [wangdahoo/vue-scroller#101]
![tim 20170628105649](https://user-images.githubusercontent.com/18752034/27618705-7b0047c6-5bf0-11e7-8ded-fac608e4f7ef.png)
怎么做可以让两个列表相互联动

**Comment by wangdahoo** [comment]
这个不是太好做，因为它的滚动动画有渐进效果。如果你真的要做的话，就通过`getPosition`方法监听前一个scroller的位置，并调用第二个scroller的scrollTo方法，但不推荐这样做。

**Comment by dnoyeb** [comment]
多谢，参考您封装控件的源码，这个需求已经搞定了。
