### ISSUE TITLE
如何监听滚动事件？

### ISSUE THREAD

**Issue by huyansheng3** [wangdahoo/vue-scroller#103]
期待滚动时，页面UI 发生一些变化，如何监听滚动事件呢？

window.addEventListener('scoll', function(){}) 这样是没有反应的，看了下元素，似乎滚动事件是自己模拟的，设置 style.transform: translateY(xx) 来实现的，所以无法触发原生的 scroll 事件，那么如何监听 scroll 事件呢？

**Comment by leonyuxiaojie** [comment]
同求 着急～ 我需要根据滚动位置处理一些ui变化

**Comment by leonyuxiaojie** [comment]
现在的处理办法 只能 
$(window).on('touchmove', function () {
   _this.scrollTop = _this.$refs.scroller.getPosition().top
})
来监听改变ui 还有没有更好的办法么

**Comment by huyansheng3** [comment]
@leonyuxiaojie  起码你这是一个解决办法了！ 没想到 touchmove 事件！赞

**Comment by wangdahoo** [comment]
@huyansheng3 看下首页文档和这个 https://github.com/wangdahoo/vue-scroller/blob/master/demo/components/SmoothingScroll.vue

**Comment by huyansheng3** [comment]
@wangdahoo  看明白了，设个定时器每50ms拿下 top 和 left 信息，根据这个信息变化下来判断是否有滚动，可以是可以。
