### ISSUE TITLE
ScrollTo方法有时候无效

### ISSUE THREAD

**Issue by huangche007** [wangdahoo/vue-scroller#109]
这是第二次提这个问题了，希望作者能够关注一下，并给点建议，上次提了很久，都没有人搭理。

一个列表组件(父组件)
initScrollEvent(){
            const _this = this;
            let startY = 0,moveY = 0,endY = 0;
             $("#tiezi-scroll").on('touchstart',(e)=>{
                 const event = e || window.event;
                 event.preventDefault();
                 startY = event.touches[0].clientY;
                 logUtil.printLog("开始滑动：",startY);
             });
             $("#tiezi-scroll").on('touchmove',(e)=>{
               const event = e || window.event;
               event.preventDefault();
               endY = event.touches[0].clientY;
               moveY = Math.abs(moveY - startY);
               logUtil.printLog("开始中.........：",moveY);
             });
             $("#tiezi-scroll").on('touchend',(e)=>{
               const event = e || window.event;
               event.preventDefault();
               _this.myCurrentPost = moveY;
               logUtil.printLog("滑动结束:",_this.myCurrentPost);
             });
         },
**这段代码主要是用来控制返回顶部按钮的显示或者隐藏**
 <backTop :pos="myCurrentPost"  v-show="!showNoData" @click="goTop"></backTop> 将上面得到的滚动位置传递的这个子组件

父组件中: goTop(){
           this.$refs.my_scroller.scrollTo(0,0,true);
         },
子组件中：
props:{
      pos:Number,
    },
    watch:{
      pos(oldV,newV){
          this.cal(oldV);
      }
    },
    methods: {
      cal(newV){
        newV > 10 ? this.show = true:this.show = false;
      },
      goTop() {
        //调用父组件的goTop方法
        this.$parent.goTop();
        this.show = false;
      }
    }

求解答，呜呜呜呜。。。。。。。。

**Comment by wangdahoo** [comment]
这里只解决本js库的相关bug，不教写代码。
