### ISSUE TITLE
在移动端使用会选不到最下方的几行

### ISSUE THREAD

**Issue by swordYWQ** [wangdahoo/vue-scroller#11]
在移动端使用会选不到最下方的几行,scroller上加了top,然后在话动到最下方的时候会会弹，导致选不到最下面的几行的

**Comment by JsBlueCat** [comment]
因为是设了外层100%定高的，比如页面内信息过大，下拉刷新就会造成一些bug。

**Comment by wangdahoo** [comment]
容器外边界用样式搞定就好了啊喂
