### ISSUE TITLE
能否加一个重置函数

### ISSUE THREAD

**Issue by baoniu** [wangdahoo/vue-scroller#111]
页面中我使用了一个scroller来加载数据
用户点击分类标签触发加载服务器数据函数
但是当一个标签数据加载完成之后，我再切换标签，将server_data数组置空时，scroller不再进行加载了，因为它执行了done(true)

**Comment by wangdahoo** [comment]
用ref标记scroller后，取vm手动用`resize`方法。最新的版本已经支持在你加入新的dom后自动`resize`了
