### ISSUE TITLE
希望增加scroller eventListener

### ISSUE THREAD

**Issue by shawerestart** [wangdahoo/vue-scroller#116]
希望滚动时增加一个eventlistener
因为遇到一个CASE就是当列表滚动时要检测是否在底部，如果在底部就不显示一个滚动到底部的按钮，如果不在底部就显示一个滚动到底部的按钮。但是好像检测不到用户触发了滚动列表的动作

**Comment by wangdahoo** [comment]
听上去好像 `getPosition()` 可以解决的样子

**Comment by muzi131313** [comment]
比如说我图片是懒加载的，懒加载的方式根据当前视野范围内进行去加载图片的，第一页超过一屏幕了，这样滚动的时候，没有地方去调用懒加载那个函数。导致图片加载不出来。这样的应用场景该怎么解决呢？
