### ISSUE TITLE
希望文档中增加提示说明当数据无更新时会触发infinite事件

### ISSUE THREAD

**Issue by leapmie** [wangdahoo/vue-scroller#120]
刚开始调试时因为没有增加对无更多数据的判断，导致不停触发infinite事件，后来才发现原来scroller中的内容无变化时会触发infinite事件，希望在文档中增加该说明。

**Comment by W285887933** [comment]
无数据的时候一直在调用后台接口  有什么办法解决吗？

**Comment by leapmie** [comment]
@W285887933 无数据时调用done(true)方法

**Comment by W285887933** [comment]
我更新到2.2.2 就好了

**Comment by YuyangGong** [comment]
@W285887933 
 感谢，有用!  但为什么文档里面没有写个方法呢？
还有一些如Scroller vm instance methods， 改怎么调用呢，如何去拿到所谓的Scroller vm instance?
在组件里this指向的是组件实例，而给其#ref也只是指向dom节点而已，这个所谓的Scroller vm instance引用拿不到呀。
