### ISSUE TITLE
切换页面后，之前页面scroller组件的infinite方法不停运行

### ISSUE THREAD

**Issue by ForeveHG** [wangdahoo/vue-scroller#123]
A和B两个页面都用到了scroller组件，第一次打A页面时是正常的，当我再切换到B页面时，A页面上的infinite方法开始不停运行，再从B页面切换到A页面上时,B页面的infinite又不停运行，搞不懂这是咋回事儿

**Comment by ForeveHG** [comment]
在我没加keep-alive之前像下面这样写是没发现问题，但是用了keep-alive后就不行了
`infinite (done) {
        setTimeout(() => {
          this.more();
          done();
        }, 1500);
      }
},`
我改成下面这样就不会不停加载了，但是上拉太快的话总是会先出现'没有更多数据'，然后才把数据加载出来
`infinite (done) {
       this.more();
        setTimeout(() => {
          done(true);
        }, 1500);
      }
},`

**Comment by wangdahoo** [comment]
@ForeveHG 如何复现你的问题？可以`pull request`吗？https://github.com/wangdahoo/vue-scroller/blob/master/demo/components/KeepAlive.vue

**Comment by hmhao** [comment]
同样遇到这个问题，就是在路由切换的时候

**Comment by ForeveHG** [comment]
@hmhao 你试试在scroller组件上加一个ref,然后再加上deactivated方法，看看行不行
`deactivated (){
      this.$refs.scroller.finishInfinite(true);
 },`
我的是不行，因为我不用keep-alive前是好的，然后我就让这两个组件不缓存，切换的时候直接`deactivated (){
      this.$destroy(true);
 },`然后又用其它办法做缓存，算是暂时解决了，你可以试试

**Comment by hmhao** [comment]
@ForeveHG 我现在这样解决了
```javascript
  data () {
    return {
      isActivated: true
    }
  },
  activated () {
    this.isActivated = true
  },
  deactivated () {
    this.isActivated = false
  },
  methods: {
    infinite (done) {
      if (!this.isActivated) return done(true)
    }
  }
```

**Comment by ForeveHG** [comment]
@hmhao 我试了我这还是不行

**Comment by hmhao** [comment]
@ForeveHG 和这个问题一样#36

**Comment by liuzhenghui** [comment]
Scroller.vue  line number ：344

          let flag = this.content.offsetHeight && this.container.clientHeight // 宽高不为0
          flag = flag && (top + 60 > this.content.offsetHeight - this.container.clientHeight )
          if (flag) {
            if (this.loadingState) return
            this.loadingState = 1
            this.showLoading = true
            this.onInfinite(this.finishInfinite)
          }

Scroller.vue  line number ：383

        let flag = width !== content_width || height !== content_height
        flag = flag && width && height // 宽高不为0
        if (flag) {
          content_width = width
          content_height = height
          this.resize()
        }

**Comment by gaojinyan** [comment]
请问有解决的方法么，我也遇到这种问题

**Comment by wangdahoo** [comment]
更新到 2.2.3 再试试

**Comment by wangdahoo** [comment]
已经在 2.2.4 中解决，查看官方demo代码。
