### ISSUE TITLE
 Uncaught SyntaxError: Unexpected reserved word

### ISSUE THREAD

**Issue by chengzhuotc** [wangdahoo/vue-scroller#128]
![4 26owkxwbzau9or608vp](https://user-images.githubusercontent.com/9107399/28818088-b0ef1b30-76dc-11e7-9da7-b9f8fc7f888c.png)

**Comment by wangdahoo** [comment]
1版本不再维护了，有问题自己搞定吧。建议迁移到v2

**Comment by chengzhuotc** [comment]
这个也是v2 是v2.0.1 ，后来我也看了，确实是v的版本升高就可以了
