### ISSUE TITLE
我怎么添加回到顶部的功能？

### ISSUE THREAD

**Issue by jimmygan** [wangdahoo/vue-scroller#13]
版本 0.4.0 
现在实现了一个体验不好的版本，即增加一个scrollingComplete的回掉方法，但是延迟很高，尤其是在“减速滑动”的时候，有没有更好的解决方案？

**Comment by wangdahoo** [comment]
没怎么看懂

**Comment by jjaimm** [comment]
同问，怎么添加回到列表顶部的功能？

**Comment by wangdahoo** [comment]
scrollTo方法

**Comment by keminu** [comment]
scrollTo方法是回到顶部，我想在滚动结束时检测是否在第一页，但是没有滚动结束时的API
