### ISSUE TITLE
初始化的加载问题！

### ISSUE THREAD

**Issue by wqq20170106** [wangdahoo/vue-scroller#131]
页面初始化的时候，通过接口动态获取数据渲染列表，此时mounted(){}和methods里边的infinite(){}方法会同时执行，就会渲染两次第一页的内容，添加限制条件不让infinite(){}方法渲染第一页时，此时页面滑动到底部之后，一直显示加载中。。。，不会执行infinite(){}方法。求原因

**Comment by wangdahoo** [comment]
回头看一下

**Comment by wangdahoo** [comment]
scroller 组件中加 `v-if`，首屏数据加载完之前为 `false`

**Comment by wangdahoo** [comment]
scroller 组件中加 `v-if`，首屏数据加载完之前为 `false`
