### ISSUE TITLE
scroller的高度问题

### ISSUE THREAD

**Issue by li-zemin** [wangdahoo/vue-scroller#134]
在官方文档中，可以设置scroller的高度的百分比，可以按照需要调节scroller的大小

先在我的页面中，有一个header，底部有一个footer；主要内容区域是一个轮播页面，然后接着是一个scroller；header和轮播的高度都是通过px，绝对大小设置的；同时，给scroller设置了style="top:  220px;"，这个220px，即为header的高度（40px）和轮播组件的高度（180px）。

这个时候，不知道scroller的高度如果是100%，就会出现这样的情况，整个页面就会被撑大，相当于在原先页面的上加上了220px，就会出现footer和header被滑动，footer可以向上偏移。我对这种情况的理解是，在页面上放不下scroller组件。

此时我调整了scroller的height的百分比，已保证可以在除去header和轮播组件外的区域中可以放下scroller，这样就可以避免上述的情况。但是如果更换设备，scroller的百分比就会不合适。如换了屏幕较小的设备，这个时候整个屏幕留给scroller的区域又会变小，可能又会出现上述的情况。

**Comment by li-zemin** [comment]
不是到为啥不能上图，最后描述一下这个bug的效果
XXXXX列表                       -----HEADER
XXXXX列表                       -----SWIPER
XXXXX列表                       -----SWIPER
-------FOOTER                  XXXXX列表
XXXXX列表                       XXXXX列表 
XXXXX列表                       XXXXX列表
XXXXX列表                       ------FOOTER 

左边是异常情况。
右边是页面刚渲染出现效果，然后下划，就可能出现右边的现象

**Comment by wangdahoo** [comment]
没有太懂
