### ISSUE TITLE
finishInifinite 执行效果

### ISSUE THREAD

**Issue by li-zemin** [wangdahoo/vue-scroller#135]
执行this.$refs.my_scroller.finishInifinite(true)后，会短暂出现（没有更多数据），但是如果列表没有渲染到底部的话，还是会继续加载数据，那有什么办法可是使加载手动停下来呢

**Comment by wangdahoo** [comment]
demo: https://wangdahoo.github.io/vue-scroller/#/loadMoreAndNoData2
code: https://github.com/wangdahoo/vue-scroller/blob/master/demo/components/LoadMoreAndNoData2.vue

may the force be with you!
