### ISSUE TITLE
在ios5还有4s机型上面的webview中，显示白屏 

### ISSUE THREAD

**Issue by well-monkey** [wangdahoo/vue-scroller#136]
开发中用了vue-scroller,但是在ios机型5 还有4s vuescroller 会显示白屏，数据并没有显示， 整个页面都成了白屏状，去掉vue-scroller 就显示正常

**Comment by shx1545** [comment]
4s可以放弃了，本来h5在移动端肯定不如 原生体验好，4s那么老得机子，就别指望了。
