### ISSUE TITLE
调用scrollTo(null,0,true)时，会出现无效的情况

### ISSUE THREAD

**Issue by jimmygan** [wangdahoo/vue-scroller#14]
版本 0.4.0
使用以下代码，调用的时候，必须要等待滑动事件结束之后，才可以调用，会出现延迟的情况，感觉上就像要点击2次，才能scrollTo指定的位置。
调用getPosition() 打印出来是之前的位置，比如从顶部滚动到底部的时候，getPosition() 获取的值是 0 ,0 。
```
back2Top(){
            this.$refs.my_scroller.getPosition()
            this.$refs.my_scroller.scrollTo(null, 0, true)
        },
```

**Comment by wangdahoo** [comment]
scrollTo(0,0,true)

**Comment by jingleo** [comment]
@wangdahoo   scrollTo(0,0,true) 需要点击两次才生效
