### ISSUE TITLE
scroller 的height 属性 使用计算属性值报错

### ISSUE THREAD

**Issue by JL-Code** [wangdahoo/vue-scroller#142]
![image](https://user-images.githubusercontent.com/14163944/29402031-04b5bf9a-8366-11e7-847a-5274e1e75bbd.png)
![image](https://user-images.githubusercontent.com/14163944/29402039-0a33c458-8366-11e7-91f9-132d8c0727a6.png)
![image](https://user-images.githubusercontent.com/14163944/29402041-0f4bfe6a-8366-11e7-8c2d-faeafec19188.png)
 
![image](https://user-images.githubusercontent.com/14163944/29402081-37cdb75c-8366-11e7-94c2-cf76fdeb4a8b.png)

**Comment by wangdahoo** [comment]
不支持变量
