### ISSUE TITLE
一个页面中放2个scroller,发生冲突

### ISSUE THREAD

**Issue by cathy1007** [wangdahoo/vue-scroller#143]
把2个div包上 <scroller>后，其中一个done(true)禁止上拉后，另一个的上拉功能同时被禁止。。。

不是demo 里的2个div在同一个页面，我写的2个div 是用v-if 、v-else 渲染的选项卡

**Comment by shx1545** [comment]
请用 v-show试试

**Comment by wangdahoo** [comment]
demo 里面不是有两个scroller 同时存在的例子吗 @cathy1007
