### ISSUE TITLE
加载更多和刷新一起的时候，当没有更多数据的时候，页面偏移量多了60px

### ISSUE THREAD

**Issue by DouBiXin** [wangdahoo/vue-scroller#144]
上拉加载更多的时候，没有更多数据，内容容器向上的偏移量多了60培px,正好是下拉刷新那个div的高度，当去掉margin-top:-60px;的时候表现良好，但是会使下拉刷新这个块显示出来

**Comment by wangdahoo** [comment]
https://github.com/wangdahoo/vue-scroller/issues/129

**Comment by HeFeng666** [comment]
@wangdahoo 我怎么感觉封装这个插件的时候scroller的内容有多加60px的内容
