### ISSUE TITLE
no-data-text 文字不显示

### ISSUE THREAD

**Issue by zhuyuanwen** [wangdahoo/vue-scroller#147]
@wangdahoo 
我git clone了项目，然后用dev跑了一下demo，试了一下LoadMoreAndNoData.vue，显示如截图所示。
“没有更多数据”可以正常显示。
![qq20170823-153839](https://user-images.githubusercontent.com/12319327/29604356-cfbdabe6-8819-11e7-8410-f28f90d67d6c.png)

然后我拷贝了LoadMoreAndNoData.vue里面的代码到自己的项目，试了一下，“没有更多数据”不能显示。
如截图所示， 在我的代码里面没有自动加上.active—— class="no-data-text active"
![qq20170823-153539](https://user-images.githubusercontent.com/12319327/29604589-998b5e14-881a-11e7-981f-eb0bf0eca45b.png)

**Comment by wangdahoo** [comment]
@zhuyuanwen 代码？

**Comment by zhuyuanwen** [comment]
`<template>
  <div>
    <h5-user-header></h5-user-header>
    <my-vr-tab></my-vr-tab>
    <scroller :on-infinite="infinite" ref="my_scroller">
      <div style="height: 219px;"></div>
      <div v-for="(item, index) in items"
          class="row" :class="{'grey-bg': index % 2 == 0}">
        {{ item }}
      </div>
    </scroller>
  </div>
</template>
<script>
  import H5UserHeader from 'components/H5UserHeader';
  import MyVrTab from 'components/MyVrTab';
  export default {
    data () {
      return {
        items: []
      }
    },
    mounted() {
      for (let i = 1; i <= 20; i++) {
        this.items.push(i + ' - keep walking, 2 be with you.')
      }
      this.top = 1
      this.bottom = 20
    },
    methods: {
      infinite(done) {
        if (this.bottom >= 30) {
          setTimeout(() => {
            done(true)
          }, 1500)
          return;
        }
        setTimeout(() => {
          let start = this.bottom + 1
          for (let i = start; i < start + 10; i++) {
            this.items.push(i + ' - keep walking, be 2 with you.')
          }
          this.bottom = this.bottom + 10;
          setTimeout(() => {
            done()
          })
        }, 1500)
      }
    }
  }
</script>`

**Comment by zhuyuanwen** [comment]
<template>
  <div>
    <h5-user-header></h5-user-header>
    <my-vr-tab></my-vr-tab>
    <scroller :on-infinite="infinite" ref="my_scroller">
      <div style="height: 219px;"></div>
      <div v-for="(item, index) in items" class="row" :class="{'grey-bg': index % 2 == 0}"> {{ item }}
      </div>
    </scroller>
  </div>
</template>
<script>
  import H5UserHeader from 'components/H5UserHeader';
  import MyVrTab from 'components/MyVrTab';

  export default {
    components: {
      H5UserHeader, MyVrTab
    },

    data () {
      return {
        items: []
      }
    },

    mounted() {
      for (let i = 1; i <= 20; i++) {
        this.items.push(i + ' - keep walking, 2 be with you.')
      }
      this.top = 1
      this.bottom = 20
    },

    methods: {
      infinite(done) {
        if (this.bottom >= 30) {
          setTimeout(() => {
            done(true)
          }, 1500)
          return;
        }

        setTimeout(() => {
          let start = this.bottom + 1
          for (let i = start; i < start + 10; i++) {
            this.items.push(i + ' - keep walking, be 2 with you.')
          }
          this.bottom = this.bottom + 10;
          setTimeout(() => {
            done()
          })
        }, 1500)
      }
    }
  }
</script>

**Comment by zhuyuanwen** [comment]
<template>
  <div>
    <h5-user-header></h5-user-header>
    <my-vr-tab></my-vr-tab>
    <scroller :on-infinite="infinite" ref="my_scroller">
      <div style="height: 219px;"></div>
      <div v-for="(item, index) in items" class="row" :class="{'grey-bg': index % 2 == 0}"> {{ item }}
      </div>
    </scroller>
  </div>
</template>
<script>
  import H5UserHeader from 'components/H5UserHeader';
  import MyVrTab from 'components/MyVrTab';

  export default {
    components: {
      H5UserHeader, MyVrTab
    },

    data () {
      return {
        items: []
      }
    },

    mounted() {
      for (let i = 1; i <= 20; i++) {
        this.items.push(i + ' - keep walking, 2 be with you.')
      }
      this.top = 1
      this.bottom = 20
    },

    methods: {
      infinite(done) {
        if (this.bottom >= 30) {
          setTimeout(() => {
            done(true)
          }, 1500)
          return;
        }

        setTimeout(() => {
          let start = this.bottom + 1
          for (let i = start; i < start + 10; i++) {
            this.items.push(i + ' - keep walking, be 2 with you.')
          }
          this.bottom = this.bottom + 10;
          setTimeout(() => {
            done()
          })
        }, 1500)
      }
    }
  }
</script>

**Comment by wangdahoo** [comment]
https://github.com/wangdahoo/vue-scroller/issues/129

may the force be with you!

**Comment by wangdahoo** [comment]
或者 你要明确定义 scroller 的高度（可以用flexbox来做）

**Comment by zhuyuanwen** [comment]
不是的，那个高度正确的。你看截图，并没有被挡住，我只要在那个块上面加css，opacity: 1 就能显示出来了

**Comment by wangdahoo** [comment]
上面的几份代码贴的是一样的？

**Comment by zhuyuanwen** [comment]
我贴了2次一样的，因为我电脑里看出来显示的效果有错误，所以我贴了2次。不过我现在手机里面看是正常的。
