### ISSUE TITLE
flexbox布局，底部固定input，输入内容插入scroller内，scroller底部出现大片空白区域

### ISSUE THREAD

**Issue by cappyli** [wangdahoo/vue-scroller#149]
使用flexbox布局，在底部固定一个input，输入法弹起后会自动把input定到输入法上边，
输入内容插入vue data内，更新scroller的内容，之后scroller的下方会出现大片空白，差不多就是输入法的高度，
刚初始化完成是正常的

**Comment by cappyli** [comment]
测试地址:
https://testapp.gwghk.com/#/chat?title=%E5%AE%A2%E6%9C%8D%E5%B0%8F%E7%A7%98%E4%B9%A6&nav=563d6eaf

**Comment by wangdahoo** [comment]
输入表单组件尽量不和这个混用吧 问题挺多的 这个主要用来展示列表
