### ISSUE TITLE
关于onInfinite的问题，在路由来回切换的时候，切换一次onInfinite就会执行一次，我并没有找到好的办法解决它

### ISSUE THREAD

**Issue by artiely** [wangdahoo/vue-scroller#151]
一般是在路由离开的时候执行onInfinite

**Comment by 472647301** [comment]
跟你一样的问题、而且我还用了keep-alive组件
我是这样解决的。你也可以试试（修改了源代码）
// enable infinite loading
    if (this.onInfinite) {
      this.infiniteTimer = setInterval(() => {
        let { left, top, zoom } = this.scroller.getValues()
        //避免页面一开始或者切换路由时执行 onInfinite 方法
        if (this.content.offsetHeight > this.container.clientHeight) { 
          if (top - 30 > this.content.offsetHeight - this.container.clientHeight) {
            if (this.loadingState) return
            this.loadingState = 1
            this.showLoading = true
            this.onInfinite(this.finishInfinite)
          }
        }

      }, 10);
    }

**Comment by wangdahoo** [comment]
更新到2.2.3再试试看

**Comment by wangdahoo** [comment]
2.2.3 有bug 试试 2.2.4。目前官方的demo已经是用keep alive模式的了 看下是不是你要的
