### ISSUE TITLE
下拉的初始判断经常为0，显示没有更多数据，可是有时候下拉时有值赋值上去的。

### ISSUE THREAD

**Issue by gaojinyan** [wangdahoo/vue-scroller#156]
![image](https://user-images.githubusercontent.com/19323149/30056311-c8804564-9264-11e7-98e0-757e48a2459a.png)

![image](https://user-images.githubusercontent.com/19323149/30056259-a0625c5c-9264-11e7-9f5b-53ee68660c31.png)
![image](https://user-images.githubusercontent.com/19323149/30056273-ab077264-9264-11e7-87be-610bd3ee6020.png)
![image](https://user-images.githubusercontent.com/19323149/30056279-b12cecd2-9264-11e7-874b-199e295464fd.png)
想问下我这样写有什么问题么，求大神回答，急

**Comment by wangdahoo** [comment]
先学习下怎么把缩进都对齐再写代码吧
