### ISSUE TITLE
 done is not a function

### ISSUE THREAD

**Issue by KaiteLiu** [wangdahoo/vue-scroller#157]
vue 项目，按照官方示例引入
`refresh1(done) {
            setTimeout(() => {
                this.getData1();
                done()
            }, 1500)
        }`
功能正常，控制台报错：
Uncaught TypeError: done is not a function
如果把done() 括号去掉就变成done is not a defined
这是因为什么呢？有遇到过相同情况的吗？

**Comment by wangdahoo** [comment]
你应该的调用该方法的时候 scroller 的 vue 实例已经被注销了，具体自己查代码。
