### ISSUE TITLE
为什么vue-scroller会自动触发下拉加载

### ISSUE THREAD

**Issue by wjryours** [wangdahoo/vue-scroller#159]
为什么vue-scroller会自动触发下拉加载on-infinite函数，我进入页面后不操作就会一条一条请求我下拉加载的请求函数，而且我的loading图标也不存在了，dom中也不存在？是vue-scroller初始化的问题么？，我的整个列表还是可以正常滑动的，大致代码如下：
`<scroller :on-infinite="infinite" ref='myscroller'>
	<div class="redpack-group-top-wrapper">
           </div>
       <div class="redpack-group-middle-wrapper">
  </div>
      <div class="redpack-group-bottom-wrapper">
<list>
.....
<list
  </div>
</scroller>
js代码
			infinite(done){
				let _this=this

				this.loadMore()
				setTimeout(()=>{
					if (_this.UserRank===false) {
						_this.noData = "没有更多数据"
						_this.$nextTick(()=>{
							
						// $('.no-data-text').css({opacity:1})
						// $(".spinner-holder").hide()
						})
						
					}
					_this.$refs.myscroller.resize();
                	done()
				},2000)
				 
			},
			loadMore(){
				if (this.UserRank===false) {
						return
					}
				this.$http({
					method:'GET',
					url:red_bumper,
					params:{id:this.$route.query.id,p:p}
				}).then((res)=>{
					if (res.data.code===403) {
						window.location.href=res.data.data.jump
					}
					
					if (res.data.code===0) {
						if(!res.data.data.data.length){
							this.UserRank=false
							return
						}
						this.ranklist=this.ranklist.concat(res.data.data.data)
						p++
					}
				})
			}
`

**Comment by shx1545** [comment]
请多多看示例，有回掉函数 done(true)

**Comment by wangdahoo** [comment]
更新到最新版本 @wjryours
