### ISSUE TITLE
卡顿

### ISSUE THREAD

**Issue by sheyunsi** [wangdahoo/vue-scroller#16]
您好，我测试了四个手机，滑动感觉卡顿，三个ios，两个安卓。 自己写的和你的demo都有测，在安卓上卡顿卡顿更明显，感觉就像丢帧一样。
然后又测了一下vonic中的scroll组件，这个不卡。

**Comment by wangdahoo** [comment]
模拟滚动和浏览器内核本来就关系很大 不是所有浏览器都带的动的
