### ISSUE TITLE
2.2.3版本有bug

### ISSUE THREAD

**Issue by toysen** [wangdahoo/vue-scroller#164]
Uncaught TypeError: Cannot read property 'doTouchStart' of undefined
Uncaught TypeError: Cannot read property 'doTouchMove' of undefined

同一套代码,2.2.0正常，2.2.3报上面的错。引用方法什么都一样。把2.2.0复盖就正常了。为什么呢？

**Comment by toysen** [comment]
刷新时候，报以上的错

**Comment by toysen** [comment]
![default](https://user-images.githubusercontent.com/29083932/30583727-6093bebc-9d5a-11e7-9a03-a94897c81d81.png)

**Comment by toysen** [comment]
![default](https://user-images.githubusercontent.com/29083932/30583809-96730d76-9d5a-11e7-9ae3-3b58445b27d5.png)

**Comment by toysen** [comment]
![default](https://user-images.githubusercontent.com/29083932/30583850-a6e0bb2c-9d5a-11e7-8b1c-1ecdc3bf7503.png)

**Comment by toysen** [comment]
![default](https://user-images.githubusercontent.com/29083932/30584834-9af9b4f0-9d5d-11e7-8812-863f9e5aec51.png)

**Comment by toysen** [comment]
![default](https://user-images.githubusercontent.com/29083932/30584946-e61361fc-9d5d-11e7-8c6d-0e13210a7eff.png)

**Comment by veaba** [comment]
坐等解决，问题可能是 属性没判断存不存在就直接用这个属性了，换了三个scroll 插件了，这个满足需求，结果出现这问题，我要气哭了。

**Comment by q27488** [comment]
对的，最新版2.2.3确实会报错；
我自己用`npm install vue-scroller@2.2.0`后退版本暂时解决。

**Comment by LeiJiXiao** [comment]
最新版2.2.3确实会报错。
![Uploading C~)_D}H@16T]C[4H[7`3R30.png…]()

**Comment by Penggggg** [comment]
vue-scroller@2.2.3 报告错误同上。
覆盖旧版本后暂时解决 yarn upgrade vue-scrollers@2.2.2

**Comment by wangdahoo** [comment]
@all 已修复 试试 v2.2.4 有问题给我留言 谢
