### ISSUE TITLE
How to click in vue-scroller comp

### ISSUE THREAD

**Issue by shenxiang11** [wangdahoo/vue-scroller#18]
`<div ref="imgWrapper">
            <div class="img-container" @click="show">
              <img class="img" src="http://pic.to8to.com/live/day_170121/20170121_a7ebc40508d40fdbfb98br7EgakxkSFN.jpg">
              <img class="img" src="http://pic.to8to.com/live/day_170121/20170121_8a8719ef2f807f6332c9I8gI3v9AZe6l.jpg">
              <img class="img" src="http://pic.to8to.com/live/day_170121/20170121_9f90855c39a463fc4655BpZgF0phNaxd.jpg">
              <img class="img" src="http://pic.to8to.com/live/day_161215/20161215_0aa7e64b0ec919c5f80dvS4ffTLwj9YD.jpg">
            </div>
          </div>`

can't click

**Comment by wangdahoo** [comment]
check online demo.

https://github.com/wangdahoo/vue-scroller/blob/master/demo/components/RefreshAndInfinite.vue#L79
