### ISSUE TITLE
容器宽高固定，元素不能滚动，请问原因是什么？

### ISSUE THREAD

**Issue by SSShooter** [wangdahoo/vue-scroller#194]
![nimbus-record-video-2017-12-13-16-33-45](https://user-images.githubusercontent.com/13051472/33929274-e33cb95c-e023-11e7-93c8-830072c6ece5.gif)

**Comment by SSShooter** [comment]
srcoller的子元素由ul改为div解决问题

**Comment by SSShooter** [comment]
不行...还是可以左右移动，求解:cry:

**Comment by VincenttHo** [comment]
为什么关了？
