### ISSUE TITLE
列表回弹机制

### ISSUE THREAD

**Issue by xuxiaohui** [wangdahoo/vue-scroller#2]
如果列表已经到达最底部，手指按住屏幕一直往上滑动直到移动到屏幕外面也不松开那么列表就不会自动回到原来的位置了

**Comment by wangdahoo** [comment]
Please show your code, and don't give a rough comment. Can't trace it.

**Comment by xuxiaohui** [comment]
touchMove(e) {
                e.preventDefault();
                if (e.touches[0].pageX < 0 || e.touches[0].pageY < 0) {
                    this.scroller.doTouchEnd(e.timeStamp)
                } else {
                    this.scroller.doTouchMove(e.touches, e.timeStamp)
                }
            }
就是e.touches[0].pageX < 0 || e.touches[0].pageY < 0（手指在屏幕外的时候）然后touchEnd列表不会回到原来的位置，我在touch Move加了一个判断，可能在touchMove里面处理会好点

**Comment by wangdahoo** [comment]
@xuxiaohui Can't catch this issue with my iPhone and Smartisan T1, close for this moment. Will be appreciated if more details provided.
