### ISSUE TITLE
infinite 方法会在首次刷新时走2遍？

### ISSUE THREAD

**Issue by youngchen1987** [wangdahoo/vue-scroller#20]
![image](https://cloud.githubusercontent.com/assets/11566474/22911659/ddf1bf9a-f29b-11e6-8197-0d389a75803f.png)
![image](https://cloud.githubusercontent.com/assets/11566474/22911661/e1cabacc-f29b-11e6-9cc1-d10b3679469f.png)

![qq 20170214095949](https://cloud.githubusercontent.com/assets/11566474/22911822/cb537648-f29c-11e6-8210-bbefab969cab.png)

打开列表页面 infinite 会被调用2次，是什么原因呢？

**Comment by wangdahoo** [comment]
自己的业务代码 我就不看了

**Comment by youngchen1987** [comment]
不算是业务问题  是这样的   如果我mounted方法中不去获取数据  直接在infinite方法中获取  就会走2遍： 我理解的是  第一次是获取数据  但是第一次获取的数据又不够一屏幕  所以获取第二次

**Comment by youngchen1987** [comment]
这个插件的原理应该就是这样的把？

**Comment by wangdahoo** [comment]
请查看官网demo代码 这里不教写代码
