### ISSUE TITLE
scrollTo不生效

### ISSUE THREAD

**Issue by wuweikd** [wangdahoo/vue-scroller#206]
**问题：**
`vm.$refs.scroller.scrollTo(0, parseInt(sessionStorage.positionTop), true)；`不生效
**现象：**
在列表加载完毕后，使用上面那句话没有生效（确定执行过）。但是如果使用按钮事件可以触发效果。
**条件：**
①在vm.$refs.scroller为true的情况下，sessionStorage.positionTop也有值的情况下，是导航栏切换路由的使用条件下
②：    `mounted () {} `没有写东西
③： 
```
infinite (done) {
        if (this.datasLength < 10) {
          /* 停止无限加载 */
          this.$refs.scroller.finishInfinite(true)
        } else {
          this.handlePage++
          this.getDatas(this.handlePage, done)// 获取数据（页码，回调）
       }
```
`  <scroller ref="scroller" id="scroller" class="my-scroller" :on-refresh="refresh" :on-infinite="infinite">
`
```

是不是使用这句函数有什么要求，比如<scroller>的定位要求？我在切换路由后，列表也不能保持原来位置。虽然没有重新加载数据。在使用keep-alive下。

**Comment by Melon0527** [comment]
setTimeout(()=>{
vm.$refs.scroller.scrollTo(0, parseInt(sessionStorage.positionTop), true)；
},100);
这样试试

**Comment by hb-bobo** [comment]
要先this.$refs.scroller.scroller.doTouchEnd(new Date())

**Comment by wuweikd** [comment]
需要延时操作，才行
