### ISSUE TITLE
引入组件报warning

### ISSUE THREAD

**Issue by BH-NOTHING** [wangdahoo/vue-scroller#216]
引入组件后就报这个错，重启项目同样报错，错误说未定义，但console.log(VueScroller)试了有内容啊
![image](https://user-images.githubusercontent.com/26459908/39910292-3070f448-5529-11e8-89ec-99976ee2f1a4.png)

![image](https://user-images.githubusercontent.com/26459908/39910241-ec43a400-5528-11e8-9553-42fd2cacb3f4.png)

**Comment by wangdahoo** [comment]
Vue.use
