### ISSUE TITLE
使用vue-scroller保持scrolltop值的问题

### ISSUE THREAD

**Issue by howyhuang** [wangdahoo/vue-scroller#25]
请教下大神 我用了这个组件
列表上拉加载了更多之后 点击列表进入子页面，或者切换view, 然后返回
vue-scroller的页面translate3d(0px, 0px, 0px)的Y值还原变成0了 这怎么解决饿

**Comment by wangdahoo** [comment]
离开前getPosition拿到位置值存好 一会回来了在拿这个值scrollTo
