### ISSUE TITLE
官网例子在PC端可以跑，但在手机微信浏览器和QQ浏览器无法运行

### ISSUE THREAD

**Issue by csdudu** [wangdahoo/vue-scroller#27]
我跑的是example/index.html这个文件，挂的是vue-scroller.min.js。并且我把所有setTimeout箭头语法改成了常规语法。发现在手机上还是不行。似乎是<scroller>这个组件有语法无法识别。

难道您这个插件是必须架上vue-cli，用babel打包成es5后才能跑？

**Comment by wangdahoo** [comment]
又爆什么错吗？QQ内置浏览器版本可能少什么polyfill吧 未严格测试多太多的版本

**Comment by wangdahoo** [comment]
未提供详细信息
