### ISSUE TITLE
发现官网的例子程序,如果上拉加载更多的时候,第一页加载没有问题,第二页loading框就不会消失了

### ISSUE THREAD

**Issue by yangxiaoxiao23** [wangdahoo/vue-scroller#28]
发现官网的例子程序,如果上拉加载更多的时候,第一页加载没有问题,第二页loading框就不会消失了

**Comment by wangdahoo** [comment]
没看懂

**Comment by manwuyu** [comment]
我来回答一下吧，我也发现的这个问题，但是是因为infinite方法的最后应该使用finishInfinite而不是resize

**Comment by yangxiaoxiao23** [comment]
@wangdahoo 
就是官网的例子, 你上拉加载更多的时候,  当第一次上拉,  loading框会隐藏,是正常的效果,但再次加载下一页的时候, loading框就不消失了.  操作一遍就能看到效果
