### ISSUE TITLE
和vue-resource用有问题

### ISSUE THREAD

**Issue by HANNAHANHAN** [wangdahoo/vue-scroller#30]
用vue-resource加载数据  程序先加载完mounted里面的数据还没开始滚动屏幕马上又加载了infinite的数据   并没有像demo一样正常加载滚动以后再加载

mounted() {
	    this.$http.get('/static/data/banner.json').then((response) => {
    		for(let i = 0 ; i < 10 ; i++ ){
    			this.items.push(response.body.card[i])
	    	}
	    },function(){
	    	console.log('error')
	    })
      this.top = 1
      this.bottom = 10
      setTimeout(() => {
        this.$refs.my_scroller.resize()
      console.log('one')
      })
    },
    methods: {
      	infinite() {
	        if (this.bottom >= 28) {
	          setTimeout(() => {
	            this.$refs.my_scroller.finishInfinite(true)
	          }, 1500)
	          return;
	        }
	        setTimeout(() => {
	          	let start = this.bottom 
	          	let all = start + 10
	          	if(all>=28){
	          		all = 28
	          	}
	          	this.$http.get('/static/data/banner.json').then((response) => {
		    		for(let i = start ; i < all ; i++ ){
		    			this.items.push(response.body.card[i])
			    	}
			    },function(){
			    	console.log('error')
			    })
	          	this.bottom = this.bottom +10;
	          	setTimeout(() => {
            		this.$refs.my_scroller.finishInfinite()
	         	})
	        }, 1500)
      	},
      
    }

**Comment by wangdahoo** [comment]
异布没处理好
