### ISSUE TITLE
infinite不会触发

### ISSUE THREAD

**Issue by mztlive** [wangdahoo/vue-scroller#31]
我发现一个问题。
在页面刚加载进来的时候infinite会触发一次
之后滑倒底部就不会再触发了。

**Comment by huxinp** [comment]
我也遇到了同样的问题

**Comment by mztlive** [comment]
暂时没找到解决方案，只能弃用先了。

**Comment by p0h5** [comment]
我遇到的是进入页面触发一次，拉到页面底部会死循环，一直加载，finish停不下来 @mztlive @huxinp ，用了其他的替代方案吗？

**Comment by wangdahoo** [comment]
重复提问

**Comment by fanyongfeng** [comment]
有同样的问题   没有看到这个问题的建议啊。。
