### ISSUE TITLE
可以加入鼠标滚动吗

### ISSUE THREAD

**Issue by shijunti19** [wangdahoo/vue-scroller#39]
PC上不是很好测试，尤其内容是连接的时候，拖动会不小心点击

**Comment by wangdahoo** [comment]
本来就有啊

**Comment by shijunti19** [comment]
@wangdahoo https://wangdahoo.github.io/vue-scroller/#/refreshAndInfinite这个只能拖动啊

**Comment by wangdahoo** [comment]
本来就是实现的就是拖动，pc端只和`mouseDown`,`mouseUp`,`mouseMove`有关。鼠标滚轮事件没打算支持。

**Comment by wangdahoo** [comment]
因为原来对mouse事件的支持，其实也只是为了方便在chrome里面调试，并不是为了让人在PC端用这个组件哦。另，点击区域非设的那么大吗。我们业务中其实也有过这种问题的，我一直认为是产品脑子不太好导致的。 @shijunti19

**Comment by shijunti19** [comment]
恩，那算了，我也是调试，另外就是放在浏览器里的作为插件话（小窗口）就需要支持滚动了

**Comment by ultraN** [comment]
@wangdahoo 请问作者，如果我想要支持鼠标滚轮事件的话，有什么思路可以提供？谢谢。因为产品必须要同时提供桌面版支持。
