### ISSUE TITLE
如果新建的是webpack项目会报Unexpected token import 错误

### ISSUE THREAD

**Issue by repe123** [wangdahoo/vue-scroller#4]
按帮助创建webpack-simple项目的话修改webpack.conf.js启动项目没有问题，但是使用webpack创建项目的话，在build/webpack.base.conf 中添加 vue-scroller的loaders，但是在进入node_modules时babel没有转换src/index.js导致了该错误

**Comment by xiaolovecai** [comment]
@repe123 小白请教下,怎么解决这个问题....

**Comment by angerlover2** [comment]
同问 Uncaught ReferenceError: Scroller is not defined

**Comment by enryzol** [comment]
但是怎么解决呢

**Comment by wangdahoo** [comment]
没懂啥意思 有代码吗？

**Comment by repe123** [comment]
readme里的实例不能用vue init webpack-simple#1 my-project，这样不能成功。  如果换成vue init webpack-simple my-project 使用vue2 去初始化，再配置好loaders，然后把demo/components里面的任意一个组件copy到APP.vue是可以跑的通的。

但是在vue init webpack my-project 的情况下，在build/webpack.base.conf  中添加配置loader 配置以及更新App.vue后， 执行webpack run dev， 控制台会报Unexpected token import。  发现vue-scroller/src/index.js没有被babel转换成es5，浏览器报错了。
尝试了多种方法去修改loaders但是均不奏效。

**Comment by wangdahoo** [comment]
刚试了一下，并没有问题。
如果是通过vue init webpack-simple#1.0 my-project 建立的项目，后续安装vue-scroller组件的时候，需要改为npm install vue-scroller@0.3.9 --save

v0.3.9 for vue 1.0 and v2.0.0 for vue 2.0+

**Comment by xiaolovecai** [comment]
@wangdahoo 通过vue-cil创建一个2.0的项目,然后再添加你的vue-scroller组件,就会报找不到vue-scroller模块的错误

**Comment by repe123** [comment]
@wangdahoo 我的问题并不是通过vue init webpack-simple#1.0 my-project，而是通过vue init webpack my-project建立项目哈。就出现 @xiaolovecai 说的错误。排查时发现node_module 中vue-scroller/src/index.js webpack引用了但是并没有使用babel进行转换。浏览器识别不了import

**Comment by JsBlueCat** [comment]
Failed to mount component: template or render function not defined. 
(found in component <scroller>) 直接引用报这个问题。目测是`vue2`的坑，`runtime-build` 不识别 `template` ，然而无法解决。。

**Comment by enryzol** [comment]
我直接把index.js那个里面的import 直接修改成 require使用。。

**Comment by wangdahoo** [comment]
貌似是这个问题 https://github.com/vuejs/vue-loader/issues/529 强力甩锅：0

**Comment by wangdahoo** [comment]
webpack 1 + vue 1，参考项目v1分支的README
webpack 2 + vue 2，参考 https://github.com/wangdahoo/vue-scroller-demo

vue init webpack my-project 生成的项目猜测是vue-loader和webpack1的兼容性问题，不是很懂，时间关系，不深究了。哪位同学有解决办法的话，欢迎给这个库https://github.com/wangdahoo/vue-scroller-demo提PR，方便别人参考，谢谢。

**Comment by chengzhuotc** [comment]
![image](https://cloud.githubusercontent.com/assets/9107399/21496673/360cf58a-cc5b-11e6-81fe-52773f9cb20d.png)
![image](https://cloud.githubusercontent.com/assets/9107399/21496676/3d2036de-cc5b-11e6-9fc6-cf1a36e3c983.png)

**Comment by darcon** [comment]
想问怎么解决的？

**Comment by shijunti19** [comment]
难怪，我昨天就遇到了，到现在都无法解决吗！

**Comment by howyhuang** [comment]
@xiaolovecai 你那问题解决了么

**Comment by wangdahoo** [comment]
下个月迁移vonic到vue2.0的时候解决这个问题，这几天暂时没空。1.0可以用v0.4.0，基本稳定了。

**Comment by wangdahoo** [comment]
vue init webpack my-project 生成的最新项目已经没有这个问题了 https://github.com/wangdahoo/vue-scroller-demo/tree/vue2%2Bwebpack1%2Bscroller2

**Comment by laden666666** [comment]
直接用webpack的umd打包，然后package.json的main去引用dist/vue-scroller.min.js这个文件，而不是src/index.js文件，是否可以解决这个问题？
