### ISSUE TITLE
使用npm集成时候，引用会出现问题

### ISSUE THREAD

**Issue by laden666666** [wangdahoo/vue-scroller#40]
使用npm集成的时候，引用会出现了问题，因为package.json里面的"main"值是"src/index.js"，而index.js是使用es6开发的。
```
import Scroller from './components/Scroller.vue'
export default Scroller
```
我的wabpack不会去解析es6的代码，所以会报错

**Comment by laden666666** [comment]
为什么不用webpack的umd打包，main指向dist中打包后的文件，这样引用应该就不会出现问题了

**Comment by wangdahoo** [comment]
@laden666666 umd是可以的，PR呗

**Comment by laden666666** [comment]
已经提交了pr

**Comment by wangdahoo** [comment]
能否不要提交dist目录下的文件，谢谢哦。

**Comment by laden666666** [comment]
好的，明天我会提交一个没有dist的pr，但是最后的dist目录还得用webpack生成一下才行，因为package.json里面的main被改为了dist里面的文件

**Comment by laden666666** [comment]
我正准备提交一个新pr，但是我看你已经把package.json的main改为了dist里面的文件，我猜我应该不用提交了。也非常感谢你能够这么快做出相应

**Comment by wangdahoo** [comment]
今天发现前一个alpha版本在iOS9⃣️下有bug 急着发包就顺便改掉了
