### ISSUE TITLE
从上一个页面进入到用vue-scroller的页面就会执行infinite函数

### ISSUE THREAD

**Issue by yksmile007** [wangdahoo/vue-scroller#46]
从工作台进入到这个列表页，上来就会执行infinite函数
`<template>
	<div id="taskcenterlist">
		<div v-title>任务中心</div>
		<div class="fixed">
			<div class="task-header mui-bar-tab">
				<v-touch tag="a" class="mui-tab-item" :class="{'mui-active' : isActive[0]}" @tap="getData(2,0)">
						待领取<i></i>
			    </v-touch>
			    <v-touch tag="a" class="mui-tab-item" :class="{'mui-active' : isActive[1]}" @tap="getData(0,1)">
			            未办结<i></i>
			    </v-touch>
			    <v-touch tag="a" class="mui-tab-item" :class="{'mui-active' : isActive[2]}" @tap="getData(1,2)">
			            已办结
			    </v-touch>
			</div>
			<div class="task-num">{{title}}任务数{{length}}个</div>
		</div>

		<scroller :on-infinite="infinite" ref="my_scroller" v-if="items.length">
			<div class="gap"></div>
			<ul class="task-tab-list" v-if="task_status==2">
				<router-link tag="a" :to="{path:urlMap[item.task_type-1],query:{ loan_id: item.loan_id,user_token: user_token,task_status:item.task_status,task_id:item.task_id,task_user_id: item.task_user_id}}" class="task-list-item" v-for="(item,index) in items">
					<div class="user-header-img" v-if="item.user_img">
						<img src="../../../imgs/header-img.png" alt="">
					</div>
					<div class="user-header-img user-no-img" :style="{'background':backgd[index%5]}" v-else>
						{{item.task_issued_user_name}}
					</div>
					<div class="user-info">
						<div class="type" v-if="item.task_type==1">{{item.task_type_text}}</div>
						<div class="type" v-if="item.task_type==2">{{item.task_type_text}}</div>
						<div class="type" v-if="item.task_type==3">{{item.task_type_text}}</div>
						<div class="user-name">
							<i class="v2_1bg icon1" v-if="index%2==0"></i><i class="v2_1bg icon2" v-else></i>{{item.first_name}}-{{item.task_issued_user_name}}
						</div>
					</div>
					<div class="task-time">
						<span class="time">{{item.stay_time}}</span>
						<span class="status" v-if="item.task_status==0">滞留</span>
						<span class="status" v-if="item.task_status==1">{{item.task_submit_time}}</span>
					</div>
				</router-link>
			</ul>
			<ul class="task-tab-list" v-if="task_status==0">
				<router-link tag="a" :to="{path:urlMap[item.task_type-1],query:{ loan_id: item.loan_id,user_token: user_token,task_status:item.task_status,task_id:item.task_id,task_user_id: item.task_user_id}}" class="task-list-item" v-for="(item,index) in items">
					<div class="user-header-img" v-if="item.user_img">
						<img src="../../../imgs/header-img.png" alt="">
					</div>
					<div class="user-header-img user-no-img" :style="{'background':backgd[index%5]}" v-else>
						{{item.task_issued_user_name | substr}}
					</div>
					<div class="user-info">
						<div class="type" v-if="item.task_type==1">{{item.task_type_text}}</div>
						<div class="type" v-if="item.task_type==2">{{item.task_type_text}}</div>
						<div class="type" v-if="item.task_type==3">{{item.task_type_text}}</div>
						<div class="user-name">
							<i class="v2_1bg icon1" v-if="index%2==0"></i><i class="v2_1bg icon2" v-else></i>{{item.first_name}}-{{item.task_issued_user_name}}
						</div>
					</div>
					<div class="task-time">
						<span class="time">{{item.stay_time}}</span>
						<span class="status" v-if="item.task_status==0">滞留</span>
						<span class="status" v-if="item.task_status==1">{{item.task_submit_time}}</span>
					</div>
				</router-link>
			</ul>
			<ul class="task-tab-list" v-if="task_status==1">
				<router-link tag="a" :to="{path:urlFinishMap[item.task_type-1],query:{ loan_id: item.loan_id,user_token: user_token,task_status:item.task_status,task_id:item.task_id,task_user_id: item.task_user_id}}" class="task-list-item" v-for="(item,index) in items">
					<div class="user-header-img" v-if="item.user_img">
						<img src="../../../imgs/header-img.png" alt="">
					</div>
					<div class="user-header-img user-no-img" :style="{'background':backgd[index%5]}" v-else>
						{{item.task_issued_user_name | substr}}
					</div>
					<div class="user-info">
						<div class="type" v-if="item.task_type==1">{{item.task_type_text}}</div>
						<div class="type" v-if="item.task_type==2">{{item.task_type_text}}</div>
						<div class="type" v-if="item.task_type==3">{{item.task_type_text}}</div>
						<div class="user-name">
							<i class="v2_1bg icon1" v-if="index%2==0"></i><i class="v2_1bg icon2" v-else></i>{{item.first_name}}-{{item.task_issued_user_name}}
						</div>
					</div>
					<div class="task-time">
						<span class="time">{{item.task_submit_time | datesubstr}}</span>
						<span class="status" v-if="item.task_status==1">{{item.task_submit_time | timesubstr}}</span>
					</div>
				</router-link>
			</ul>
		</scroller>
		<div v-show="isShownonpage" class="order-uncon">
			<div class="order-unconbg"></div>
			<p class="order-unconmsg">这里没有相关记录呢~</p>
		</div>
	</div>
</template>
<script>
	import Scroller from 'vue-scroller'
	export default{
		components: {
			Scroller
		},
		data(){
			return {
				isShownonpage:false,
				isActive:[],
				no_img_count:0,
				page:1,
				data:[],
				items:[],
				length:'',
				title:'',
				titleId:this.$route.query.titleid,
				user_token:this.$route.query.user_token,
				task_status:this.$route.query.task_status,
				urlMap:['/riskControl','/contactUser','/getAssetsDetail'],
				urlFinishMap:['/lookRiskTaskCompleted','/contactUser','/lookTaskList'],
				titleArr:['待领取','未办结','已办结'],
				backgd:['#0ea3f0','#f19ec2','#b3d465','#f8b551','#8c97cb']
			}
		},
		mounted(){
			this.getInitData();
		},
		methods:{
			getInitData,
			getData,
			infinite,
			getInfiniteData
		},
		
		filters:{
			substr(val){
				if(val == '') return;
				return val.substring(val.length-2);
			},
			timesubstr(val){
				if(val == '') return;
				return val.substring(val.length-8);
			},
			datesubstr(val){
				if(val == '') return;
				return val.substring(5,10);
			},
		},
		

	}

	function infinite() {
		var _this = this;
		if (_this.hasmore == 0) {
			setTimeout(() => {
				_this.$refs.my_scroller.finishInfinite(true);
			}, 1500)
			return;
		}
		
		setTimeout(() => {
			_this.page = _this.page + 1;

			_this.getInfiniteData();

			setTimeout(() => {
				_this.$refs.my_scroller.finishInfinite()
			})
		}, 1000)
	}

	//初始化列表信息
	function getInitData(){
		let taskUrlIndex = JSON.parse(this.$localStorage.get('taskUrlIndex'));
		if(taskUrlIndex){
			this.titleId = taskUrlIndex.title_id;
			this.task_status = taskUrlIndex.task_status;
		}
		this.isActive[this.titleId] = true;
		this.title = this.titleArr[this.titleId];
		this.$http.get(this.$store.state.apiUrl+'/task/getTaskList?user_token='+this.user_token+'&task_status='+this.task_status+'&page='+this.page+'&pageSize=10').then((response) => {
			response = response.body;
			if(response.code == 0){
				this.data=response.data.task_list;
				this.hasmore = response.hasmore;
				this.data.forEach((item,index) => {
					this.items.push(item);
					if(item.user_header_img == '' || item.user_header_img == null){
						this.no_img_count ++;
					}
				})
				this.$nextTick(function(){
					setTimeout(() => {
						this.$refs.my_scroller.resize()
					})
				})
				this.length = this.items.length;
				if(this.items.length==0){
					this.isShownonpage = true;
				}else{
					this.isShownonpage = false;
				}
			}

		})
	}
	//列表信息
	function getInfiniteData() {
			this.$http.get(`${this.$store.state.apiUrl}/task/getTaskList?user_token=${this.user_token}&task_status=${this.task_status}&page=${this.page}&pageSize=10`).then((response) => {
	    		response = response.body;
	    			if(response.code == 0){
		    			this.data = response.data.task_list;
		    			this.data.forEach((item,index) => {
							this.items.push(item);
						})
						this.$nextTick(function(){
							setTimeout(() => {
								this.$refs.my_scroller.resize()
							})
						})
						this.hasmore = response.hasmore;
						this.length = this.items.length;
		    			if(this.items.length==0){
		    				this.isShownonpage=true;
		    			}else{
		    				this.isShownonpage=false;
		    			}			
		    		}	
		    		else{
		    			console.log("请求失败！！！");
		    		}	
		   	 })
		}
	//列表信息
	function getData(index,code) {
		// &page=1&pageSize=5
			let urlObj = JSON.stringify({"task_status":index,"title_id":code})
			this.$localStorage.set('taskUrlIndex',urlObj);
			this.page=1;
			this.items = [];
			this.title = this.titleArr[code];
			/*this.$refs.my_scroller.finishInfinite();*/
			this.$http.get(`${this.$store.state.apiUrl}/task/getTaskList?user_token=${this.user_token}&task_status=${index}&page=${this.page}&pageSize=10`).then((response) => {
	    		response = response.body;
	    			if(response.code == 0){
	    				this.task_status = index;
		    			this.data = response.data.task_list;

		    			this.data.forEach((item,index) => {
							this.items.push(item);
						})

						this.$nextTick(function(){
							setTimeout(() => {
								this.$refs.my_scroller.resize()
							})
						})
						this.hasmore = response.hasmore;
						this.length = this.items.length;
		    			if(this.items.length==0){
		    				this.isShownonpage=true;
		    			}else{
		    				this.isShownonpage=false;
		    			}
		    			//重置当前数组状态
		    			this.isActive=[];
		    			this.isActive[code]=true;    			
		    		}	
		    		else{
		    			console.log("请求失败！！！");
		    		}	
		   	 })
		}
	
</script>`

**Comment by uncleLian** [comment]
一进入页面没数据的时候会触发infinite方法,我不希望如此，当keep-live保存组件状态的时候，切换到其他路由页面， 就会一直不断触发infinite！！！ 希望有个 禁止infinite的方法

**Comment by wangdahoo** [comment]
#53
