### ISSUE TITLE
Cant use directly with webpack 2 and vue 2, throw "Couldn't find preset 'es2015'"

### ISSUE THREAD

**Issue by JonasGao** [wangdahoo/vue-scroller#52]
## Condition 
vue-router@2.3.0
vue-scroller@2.1.2
vue@2.2.6
webpack@2.x

## My step:
1. npm install vue-scroller
2. import Scroller from 'vue-scroller' ( in my vue component )
3. declare components object ```components: {Scroller}``` ( in my vue component )
4. write html ```<scroller><div v-for="..."></div></scroller>```
5. preview

## Then
Module build failed: Error: Couldn't find preset "es2015" relative to directory "/Users/jonas/Documents/VoyageOne/offshore2/offshore-mobile/client-webchat/src/main/webapp/node_modules/vue-scroller"

## And
I see your [babelrc in your demo](https://github.com/wangdahoo/vue-scroller-demo/blob/master/.babelrc)

Maybe you need a "per-dependency" in your package.json

**Comment by wangdahoo** [comment]
@JonasGao 

```js
import Vue from 'vue'
import VueScroller from 'vue-scroller'
vue.use(VueScroller)
// your magic goes below
```

https://github.com/wangdahoo/vue-scroller-demo
