### ISSUE TITLE
大神，关于进入页面会执行infinite函数的BUG整理

### ISSUE THREAD

**Issue by Jack-93** [wangdahoo/vue-scroller#53]
追查了下代码，发现infinite的触发是在定时器里面，`if (this.onInfinite) {
        this.infiniteTimer = setInterval(() => {
          let {left, top, zoom} = this.scroller.getValues()
          if (top + 60 > this.content.offsetHeight - this.container.clientHeight) {
            if (this.loadingState) return
            this.loadingState = 1
            this.showLoading = true
            this.onInfinite()
          }
        }, 10);
      }`
当第一次进入页面，没有数据时，top + 60 > this.content.offsetHeight - this.container.clientHeight。于是执行了infinite，
我临时采用的方法是把infinite的触发放到touchEnd事件之中，希望有大神能找出更好多方法，指点下

**Comment by wangdahoo** [comment]
如果你是进入页面后，需要等ajax返回数据才能渲染出列表的话，自己控制在没有初始化数据前不显示组件就好了呗。

`<scroller v-if="!isNoDataToRender">...</scroller>`
