### ISSUE TITLE
2.2.0 版本报错

### ISSUE THREAD

**Issue by wYhooo** [wangdahoo/vue-scroller#58]
控制台错误信息如下：
`[Vue warn]: Failed to mount component: template or render function not defined. 
(found in <Scroller>)`

试了一下，之前的 2.1.2 就没有这个问题。
Vue 和其他组件的版本都是最新版本。

**Comment by wangdahoo** [comment]
`vue init webpack your-app` 起的项目？

**Comment by wangdahoo** [comment]
@wYhooo 刚重新试了一下，没发现有什么问题。下次反应问题的话，希望提供更多的细节。

**Comment by wYhooo** [comment]
@wangdahoo 我建了个仓库
https://github.com/wYhooo/test-vue-scroller

这个问题是我写在单文件组件里时出现的，仓库里的代码基本是从你的 jsfiddle 里复制的。
如果我哪里写错了还请指出，多谢。

**Comment by wYhooo** [comment]
话说我还有个问题。。。
[这里](https://github.com/wangdahoo/vue-scroller/blob/master/demo/components/RefreshAndInfinite.vue#L52) 
如果不检查一下 done 的存在的话，不会报错么。。。

**Comment by wangdahoo** [comment]
回头看一下

**Comment by wangdahoo** [comment]
@wYhooo 引入方式不对，请看下项目首页 README

**Comment by overtrue** [comment]
今天我也遇到这个问题了，之前一切正常使用，突然就坏了，@wangdahoo 所以是引入方式改了咯？

**Comment by overtrue** [comment]
@wangdahoo 按语言化版本的规则，这样的破坏性变化应该变大版本号吧，从 2.1.2 到 2.2.0 就不能用了这不符合正确的发版规则吧。参考：http://semver.org/lang/zh-CN/

> 版本格式：主版本号.次版本号.修订号，版本号递增规则如下：
>
>主版本号：当你做了不兼容的 API 修改，
>次版本号：当你做了向下兼容的功能性新增，
>修订号：当你做了向下兼容的问题修正。

**Comment by wangdahoo** [comment]
@overtrue 那个只是guideline嘛 还是想保持大版本号为2，1 => vue 1，2 => vue 2

**Comment by wangdahoo** [comment]
@overtrue 生产环境下 一般都锁定版本吧

**Comment by overtrue** [comment]
@wangdahoo 嗯，但是就算是开发环境我还是被这个问题搞了好久，所以，建议还是按 semver 来，或者，就算要保持版本号，也最好在 changelog 写好变更，比如在发版日志里写好，至少减少时间。
