### ISSUE TITLE
你好finishPullToRefresh这个方法该如何调用

### ISSUE THREAD

**Issue by GemVinci** [wangdahoo/vue-scroller#59]
网上查的下面3种方式都可以调用 finishPullToRefresh 方法
但是貌似都不起作用
 this.$broadcast('$finishPullToRefresh')
 $scroller.get('myScroller').finishPullToRefresh()
 this.$refs.my_scroller.finishPullToRefresh()

看你demo 用done(true)就可以 结束加载动画

**Comment by wangdahoo** [comment]
用 done 回调 或者 通过 this.$refs 拿到 scroller vm  实例后调用 finishPullToRefresh 方法都是可以的
