### ISSUE TITLE
请问我这里一直回调onInfinite函数是什么问题啊

### ISSUE THREAD

**Issue by ygh1** [wangdahoo/vue-scroller#60]

**Comment by ygh1** [comment]
onInfinite(done) {
    		setTimeout(() => {
				console.log(222);
	          done(false)	
	        }, 1500)
    	}

控制台一直在输出222，并且我的页面无法向上滑动，就是我用鼠标往上拖，然后页面自己又掉下来了

**Comment by wangdahoo** [comment]
#57
