### ISSUE TITLE
当完成done(true)时，是否可以重新开启，类似于refresh的功能？

### ISSUE THREAD

**Issue by bsxz0604** [wangdahoo/vue-scroller#62]
`setTimeout(function () {done(true);}, 1500);`

完成这一步后，想切换数据，重新启用infinite

**Comment by wangdahoo** [comment]
demo不就是这样的吗？https://wangdahoo.github.io/vue-scroller/#/loadMoreAndNoData

ps: 需要像下拉刷新那样的话，可以在展示完“没有更多数据”若干时间后，手动调用`scrollTo`方法将容器滑动到底部适当位置
