### ISSUE TITLE
Cannot read property 'Animate' of undefined

### ISSUE THREAD

**Issue by Mywifi** [wangdahoo/vue-scroller#64]
当项目中引用了babel-polyfill时，就会报这个错；
原因是core.js中设置了一个全局的作用域 window.core，刚好babel-polyfill也给window.core赋值了，导致core被重置为babel-polyfill的，于是报错。

**Comment by wangdahoo** [comment]
好的 回头看下这个问题 谢谢反馈

**Comment by wangdahoo** [comment]
@Mywifi `yarn add vue-scroller@2.2.1-beta.2 -S` 试试这个，没问题的话，晚点发正式包。

**Comment by wangdahoo** [comment]
@Mywifi 等你回复再关闭吧

**Comment by Mywifi** [comment]
可以了
