### ISSUE TITLE
你好，为啥会自动infinite

### ISSUE THREAD

**Issue by yanyongchao** [wangdahoo/vue-scroller#69]
你好，为啥会自动infinite

**Comment by yanyongchao** [comment]
<div class="tab">
      <router-link to="/list/order">全部订单</router-link>
      <router-link to="/list/draft">草稿箱</router-link>
</div>
到草稿箱页面，全部订单会加载所有数据，

**Comment by wangdahoo** [comment]
https://github.com/wangdahoo/vue-scroller/issues/53
