### ISSUE TITLE
加上scroller之后，列表中overflow:auto 属性失效

### ISSUE THREAD

**Issue by yuzhou423** [wangdahoo/vue-scroller#72]
滚动列表中，每行有多张图片，超出使用overflow:auto 进行隐藏，同时显示滚动条，在不加scroller组件之前，用手可以左右滚动，但是加了scroller之后，无法左右滚动了！还望作者指明方向！

**Comment by wangdahoo** [comment]
本来就只做一个方向（水平或垂直）的滚动，具体查看首页文档。按你的需求来看，这仿佛并不是你所需要的。

**Comment by kevinchung1984** [comment]
我也有这需求，既用了本组件的垂直滚动的刷新和加载，但水平方向又有多张图片，需要overflow:auto，可以水平滑动，目前看好像本组件限制了图片的水平滚动

**Comment by ChristianZhou** [comment]
+1
