### ISSUE TITLE
你好请教问题

### ISSUE THREAD

**Issue by alasai** [wangdahoo/vue-scroller#75]
我用了你这个组件，我现在想记住返回列表的位置，但是
当点击某个新闻明细时触发下面事件
beforeRouteLeave (to, from, next) {

      alert(document.body.scrollTop)  
      next()
    }

但是这里面的document.body.scrollTop获取的总是0，请问应该怎么解决呢

**Comment by shuangbofu** [comment]
想获取位置，用他提供的api也就是getPosition()

**Comment by wangdahoo** [comment]
@alasai 请查看项目首页文档
