### ISSUE TITLE
导致iOS上自带的原生界面的左划返回效果失效

### ISSUE THREAD

**Issue by jasperchou** [wangdahoo/vue-scroller#77]
估计是handle了左右滑动的事件，导致iOS上自带的原生界面的左划返回效果失效。有什么办法可以兼容下吗？

**Comment by wangdahoo** [comment]
你仿佛在逗我笑

**Comment by jasperchou** [comment]
加条透明边即可。

ps：态度真恶心。论技术你前端可能还可以，论心态就一渣渣。

**Comment by wangdahoo** [comment]
@jasperchou 就是特别喜欢恶心你这种不懂怎么提`issue`，还特喜欢瞎bb的
