### ISSUE TITLE
在activated中使用scrollTo无效

### ISSUE THREAD

**Issue by shuangbofu** [wangdahoo/vue-scroller#78]

**Comment by wangdahoo** [comment]
比如？贴个代码呗

**Comment by free46000** [comment]
这样是无效的：
activated () {
      const self = this
      self.$refs.scroll.scrollTo(0, 100, false)
}
=====================================
但是加上延时就有效了，如下代码：
activated () {
      const self = this
      setTimeout(function () {
        self.$refs.scroll.scrollTo(0, 100, false)
      }, 1000)
}

**Comment by xty1992a** [comment]
$nextTick()试试

**Comment by hmhao** [comment]
activated中，在调用scrollTo前先调用一下resize。例如：
```javascript
  activated () {
    this.$nextTick(() => {
      this.$refs.scroller.resize()
      this.$refs.scroller.scrollTo(0, 100, false)
    })
  }
```
