### ISSUE TITLE
如何取消done(true)状态？

### ISSUE THREAD

**Issue by shenghy** [wangdahoo/vue-scroller#82]
如何取消done（true）状态，让下来重新开启？

**Comment by wangdahoo** [comment]
页面往下滑动后，再次往上滑（上滑只往下翻页面）又会重新`loading more`。这是目前的交互设定。

**Comment by iampcfox** [comment]
> 页面往下滑动后，再次往上滑（上滑只往下翻页面）又会重新`loading more`。这是目前的交互设定。

我觉得你应该在 readme 标注一下，我找了好多issues才找到你这句话…
