### ISSUE TITLE
当数据只有一条并没有更多数据的时候，而scroller的height=100%的话 组件就会自动再次上拉加载，能不能禁止这个上拉加载事件？

### ISSUE THREAD

**Issue by Jaction** [wangdahoo/vue-scroller#83]
当数据只有一条并没有更多数据的时候，
而scroller的height=100%的话 组件就会自动再次上拉加载，
能不能禁止这个上拉加载事件？

不然的话 他就会一直加载到数据超过这个100%高度 才停止

很急，求大神解答

![image](https://cloud.githubusercontent.com/assets/17811893/26389859/8e93f6e8-408e-11e7-9861-38fb8fc9787b.png)

**Comment by tong36** [comment]
试试这个`done(true)`

**Comment by Jaction** [comment]
什么done(true) 不懂你的意思  能写段代码吗？

**Comment by tong36** [comment]
https://jsfiddle.net/wangdahoo/cpjfr096/
在`infinite`里面写上'done(true)',`retuen`，试试看，行不行。

**Comment by tong36** [comment]
https://jsfiddle.net/wangdahoo/cpjfr096/
在infinite里面写上`done(true)`,`retuen`，试试看，行不行。

**Comment by wangdahoo** [comment]
楼上正解

**Comment by Jaction** [comment]
```
// 上拉
            infinite() {
                if (done(true)) {
                    return;
                }
                this.$parent.page ++;
                this.$parent.isRefresh = false;
                setTimeout(()=> {
                    this.$parent.getDataList();
                    if (this.$refs.scrollList) {
                        this.$refs.scrollList.finishInfinite();
                    }
                    if (this.moreData) {
                        this.$refs.scrollList.finishInfinite(true);
                    }
                }, this.duration);
            }
```

这样吗
![image](https://cloud.githubusercontent.com/assets/17811893/26390935/4708e04a-4093-11e7-835a-bb4ffc1dad8b.png)

**Comment by Jaction** [comment]
done(true) 直接报错的，能在我这个代码上看一下怎么添加吗?

**Comment by tong36** [comment]
`infinite() {
                done(true)
return
            }`

**Comment by Jaction** [comment]
![image](https://cloud.githubusercontent.com/assets/17811893/26391353/ea0e6e12-4094-11e7-8aed-b20d2c6b5648.png)


![image](https://cloud.githubusercontent.com/assets/17811893/26391341/e2b70c14-4094-11e7-9550-038b7f9f8536.png)

直接报done错误了

**Comment by Jaction** [comment]
你发给我的链接https://jsfiddle.net/wangdahoo/cpjfr096/  我打不开

**Comment by tong36** [comment]
`infinite(done) { done(true) return }`
地址翻墙试试

**Comment by Jaction** [comment]
当我请求数据的条码为1 每次只请求一条数据，仍然不足height=100%的高度，还是会重复上拉刷新

**Comment by tong36** [comment]
当出现你说的情况是，执行
`done(true)`
`return`
试试

**Comment by Jaction** [comment]
```
            // 上拉
            infinite(done) {
                console.log(done(true));
                if (done(true)) {
                    console.log(1);
                    return;
                }
                this.$parent.page ++;
                this.$parent.isRefresh = false;
                setTimeout(()=> {
                    this.$parent.getDataList();
                    if (this.$refs.scrollList) {
                        this.$refs.scrollList.finishInfinite();
                    }
                    if (this.moreData) {
                        this.$refs.scrollList.finishInfinite(true);
                    }
                }, this.duration);
            }
```
我试着打印出 参数中的 console.log( done(true) ) 还是报undefined错误

![image](https://cloud.githubusercontent.com/assets/17811893/26395756/b3f6002e-40a3-11e7-9002-79150591f346.png)

![image](https://cloud.githubusercontent.com/assets/17811893/26395666/60c3e70e-40a3-11e7-910b-9b017b05cd2e.png)

**Comment by tong36** [comment]
`javascript`
`infinite: function(done) {
          if('') {
            done(true)
            return
          }
        }`
if判断条件自己写
