### ISSUE TITLE
无限加载，没有更多数据时能不能让组件适中保持无数据？

### ISSUE THREAD

**Issue by holdno** [wangdahoo/vue-scroller#85]
无限加载，没有更多数据时调用done(true)能不能让组件适中保持无数据？  
现在的情况是显示没有更多，但是往上滑一下再回来，又发了一次请求来判断是否有无数据

**Comment by Paulhejia** [comment]
如果 没有触发 下拉 刷新， 可以用一个值保存 无数据状态 ，true 时 done(true).
 下拉刷新 是 应该  重新 刷新 列表请求数据的，如果数据是不断 变动的话，如果 不变的话我 ，也是可以用这个无数据状态的值来 防止 异步请求的

**Comment by wangdahoo** [comment]
同上
