### ISSUE TITLE
只用一两条数据的时候，会显示loading图标，如何解决？

### ISSUE THREAD

**Issue by chenkongming** [wangdahoo/vue-scroller#87]

**Comment by Paulhejia** [comment]
用 
![image](https://user-images.githubusercontent.com/19368190/27141702-7a288308-515b-11e7-8cb9-fb249a63c214.png)

`this.$refs.scroll. finishPullToRefresh()`  隐藏页顶部的loading
`this.$refs.scroll. finishInfinite()`  隐藏页底部的loading
`this.$refs.scroll. finishInfinite(true)`  隐藏页底部的loading ,显示无更多数据，代表禁止再触发`onInfinite`

**Comment by greedying** [comment]
@Paulhejia  我试了下，似乎 finishInfinite也没用，哎- -

**Comment by jjjachyty** [comment]
done(true)

**Comment by wangdahoo** [comment]
升级到最新版本呢
