### ISSUE TITLE
我<scroller>标签之内的内容改变为什么会触发infinite函数，怎么才能禁止

### ISSUE THREAD

**Issue by wangyanchen** [wangdahoo/vue-scroller#90]
` <scroller :on-refresh="refresh"
                :on-infinite="infinite"
                refresh-layer-color="#4b8bf4"
                loading-layer-color="#ec4949">
 <panel :list="chooseList" type="1"></panel>
</scroller>
`
当chooseList的值发生改变时，会自动执行infinite函数

**Comment by Paulhejia** [comment]
`<scroller  [ref = "scroll"](url)    :on-refresh="refresh" :on-infinite="infinite" refresh-layer-color="#4b8bf4" loading-layer-color="#ec4949"> <panel :list="chooseList" type="1"></panel> </scroller>`
用` this._self.$refs.scroll.finishInfinite(true)` 这样 当上拉加载没有内容时就不会 再触发 infinite
当再次下拉时 再用  `this._self.$refs.scroll.finishInfinite()` 可以重新唤醒 上拉时触发 infinite

**Comment by wangdahoo** [comment]
实现机制就是这样，不能禁止
