### ISSUE TITLE
:on-infinite 无法终止执行

### ISSUE THREAD

**Issue by Zenfeder** [wangdahoo/vue-scroller#91]
@wangdahoo hello，infinite触发之后根本停不下来，页脚一直在转菊花，请问这个问题如何解决。（代码如下图）

![image](https://user-images.githubusercontent.com/4090900/26970027-6cb667e6-4d3a-11e7-9009-70fe1639f855.png)

**Comment by greedying** [comment]
co-ask

**Comment by Wulawa** [comment]
+1

**Comment by jjjachyty** [comment]
done(true);

**Comment by huangche007** [comment]
怎么停不下来，可以停下来的在刷新和加载更多的方法参数done就是做这个事儿的

**Comment by Zenfeder** [comment]
@huangche007 如图，我在定时器里加了done呀，确实停不下来，你可以把我这段代码敲下试试，，，算了，我自己封装了个

**Comment by jjjachyty** [comment]
@Zenfeder  done(true) not done()

**Comment by muzi131313** [comment]
@jjjachyty 建议更新下[vue-scroller-demo](https://github.com/wangdahoo/vue-scroller-demo/blob/master/src/App.vue)

**Comment by wangdahoo** [comment]
@Zenfeder 
https://github.com/wangdahoo/vue-scroller/blob/master/demo/components/LoadMoreAndNoData.vue#L39

@jjjachyty j 谢
