### ISSUE TITLE
当列表数据不足以撑满整个页面的时候on-infinite方法会无限执行下去

### ISSUE THREAD

**Issue by liusome** [wangdahoo/vue-scroller#97]
```
async infiniteLoad (done) {
      let vm = this;
      vm.page = vm.page+1;
      const topicData = await vm.initTopicDate();
      if(vm.hasnextpage){
        done(true);
        vm.$refs.indexScroller.finishInfinite(true);
      }
      vm.weiBos = [...vm.weiBos,...topicData];
      setTimeout(() => {
        done()
        vm.$refs.indexScroller.finishInfinite();
      },1500)
    }
```
![image](https://user-images.githubusercontent.com/13285305/27218382-8ac7bf48-52b0-11e7-9d2c-bfc735c1e897.png)

**Comment by liusome** [comment]
通过 return 临时解决了这个问题

**Comment by greedying** [comment]
根据我实验， #83  才是正确答案

**Comment by alasai** [comment]
@greedying 那个解决方案我看了，也没看到最终的答案，请问你的代码是怎么写

**Comment by baoniu** [comment]
api.getArticleList(this.page).then(
                    res => {
                        if (res.data.length > 0) {  //返回数据条数大于0 
                           this.$set(this, 'server_data', this.server_data.concat(tmp));
                            ++this.page;
                            done();
                        } else { //返回数据条数 === 0
                            done(true);   //传true时，不会再加载了
                        }
                    },
                    p_obj => {
                        done(true);
                    }
                )

**Comment by alasai** [comment]
同问，请问大家是怎么解决的，
infinite(done) {
        this.counter=this.counter+1
        var that = this
        setTimeout(function () {
          util.get(`Message/messages?tab=`+that.$route.query.tab+`&page=`+that.counter+'&time=', {}, ({data}) => {
            if(data.length==0)
            {
              this.$refs.my_scroller.finishInfinite(true);
              setTimeout(() => {
                done(true)
              }, 100)
            }else
            {
              data.forEach((item) => that.items.push(item))
              done(false)
            }
          })
        }, 500)
      }
这样写都没用

**Comment by alasai** [comment]
@wangdahoo 请问怎么解决呢，这个问题好像是很多人都面临的问题

**Comment by greedying** [comment]
@alasai,  done(true)  啊

**Comment by alasai** [comment]
@greedying 我上面的代码你看了吗，已经加了啊
infinite(done) {
this.counter=this.counter+1
var that = this
setTimeout(function () {
util.get(Message/messages?tab=+that.$route.query.tab+&page=+that.counter+'&time=', {}, ({data}) => {
if(data.length==0)
{
this.$refs.my_scroller.finishInfinite(true); --这里
setTimeout(() => {
done(true)            --还有这里
}, 100)
}else
{
data.forEach((item) => that.items.push(item))
done(false)
}
})
}, 500)
}

**Comment by greedying** [comment]
没看，谁看你代码




发自网易邮箱大师
在2017年07月12日 08:46，alasai 写道：

@greedying 我上面的代码你看了吗，已经加了啊
infinite(done) {
this.counter=this.counter+1
var that = this
setTimeout(function () {
util.get(Message/messages?tab=+that.$route.query.tab+&page=+that.counter+'&time=', {}, ({data}) => {
if(data.length==0)
{
this.$refs.my_scroller.finishInfinite(true); --这里
setTimeout(() => {
done(true) --还有这里
}, 100)
}else
{
data.forEach((item) => that.items.push(item))
done(false)
}
})
}, 500)
}

**Comment by skylinety** [comment]
这个问题是有点烦人，但是作者这么设计还是算不上bug，因为一个页面如果所有数据都占不满，那么根本没有必要下拉刷新，作者的设计思路应该是当数据占满整个页面的时候，才能有下拉操作。所以会不停地发请求，大家分页的时候每页限制条数多设定一点就不会有这个问题了。但是应该提出来，害得我找了好久。

**Comment by skylinety** [comment]
@alasai 这个问题，如果是发请求加载数据，建议把每次取得结果的条数设定多一点，让一次的数量能够铺满整个页面，如果一次不够一个页面，用户不会知道还有数据，可能不会下拉，所以作者会设计成不停执行，直到铺满页面，才会停止。

**Comment by alasai** [comment]
@skylinety 没用，如果你从服务器只获取到一条数据，他还是执行第二页加载

**Comment by wangdahoo** [comment]
升级到最新版本 `v2.2.2`

**Comment by feng003** [comment]
@wangdahoo v2.2.2  有处理 数据不足的时候 会有两次请求吗？就是如何处理数组不足  不触发infinites事件呢？
