### ISSUE TITLE
ScrollTo方法有时候无效

### ISSUE THREAD

**Issue by huangche007** [wangdahoo/vue-scroller#99]
在最近的项目中使用了vue-scroller，有这样一个场景，当滑动列表的时候，返回顶部按钮就出现，然后点击该按钮我就调用了scrollTo方法，但有时候无效。

代码:
按钮组件(backTop.vue):
<a class="icon-top" v-show="show" @click="goTop">x</a>
 methods: {
      cal(newV){
        newV > 100 ? this.show = true:this.show = false;
      },
      goTop() {
        this.$parent.goTop();
        this.show = false;
      }
    }
列表组件:
 methods:{
         goTop(){
           this.$refs.my_scroller.scrollTo(0,0,true);
         },
}

**Comment by wangdahoo** [comment]
https://github.com/wangdahoo/vue-scroller/blob/master/demo/components/SmoothingScroll.vue
